name: "PR checks"
on:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test_lint_and_build:
    name: "Lint sources and check build artifacts"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6.1.0
        with:
          node-version: "20.x"
      - run: npm install && npm run lint
      - run: npm run build && git diff --exit-code
